eureka:
  client:
    serviceUrl:
      defaultZone: https://registry-service-cn.herokuapp.com/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: task-service
          uri: http://task-service-cn.herokuapp.com
          predicates:
           - Path=/task/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
        - id: backlog-service
          uri: https://backlog-service.herokuapp.com
          predicates:
            - Path=/backlogs/**